import 'package:flutter_riverpod/flutter_riverpod.dart';

// Toggles between 'en' and 'kn'
final languageProvider = StateProvider<String>((ref) => 'en');

// English strings
const Map<String, String> _enStrings = {
  'home': 'Home',
  'jobs': 'Jobs',
  'profile': 'Profile',
  'apply': 'Apply',
  'urgent': 'Urgent',
  'open': 'Open',
  'assigned': 'Assigned',
  'in_progress': 'In Progress',
  'completed': 'Completed',
  'cancelled': 'Cancelled',
  'worker': "I'm a Worker",
  'employer': "I'm an Employer",
  'search_grow': 'Search & Grow Your Career',
  'recommended': 'Recommended Jobs',
  'my_jobs': 'My Posted Jobs',
  'per_day': '/day',
  'away': 'away',
  'workers_needed': 'Workers Needed',
  'start_date': 'Start Date',
  'wage': 'Wage',
  'description': 'Description',
  'applicants': 'applicants',
  'filter': 'Filter',
  'apply_filters': 'Apply Filters',
  'status': 'Status',
  'wage_range': 'Wage Range',
  'core_skills': 'Core Skills',
  'recent_reviews': 'Recent Reviews',
  'experience': 'Experience',
  'jobs_completed': 'Jobs Done',
  'reliability': 'Reliability',
  'applied': 'Applied!',
  'apply_success': 'Application submitted successfully',
  'post_job': 'Post Job',
  'coming_soon': 'Coming soon',
  'years': 'Yrs',
  'km_away': '~5 km away',
  'reset': 'Reset',
  'post_job_title': 'Post a job',
  'edit_job_title': 'Edit job',
  'wizard_step_1': 'What & where',
  'wizard_step_2': 'When & how many',
  'wizard_step_3': 'Pay & confirm',
  'next': 'Next',
  'back': 'Back',
  'cancel': 'Cancel',
  'job_category': 'Category',
  'job_title_field': 'Job title',
  'job_description': 'Description (optional)',
  'pick_location': 'Pick location',
  'use_my_location': 'Use my location',
  'adjust_on_map': 'Adjust on map',
  'type_address': 'Type address',
  'start_time_field': 'Start time',
  'end_time_field': 'End time',
  'end_date': 'End date',
  'workers_count': 'Workers needed',
  'mark_urgent': 'Mark as urgent',
  'preview': 'Preview',
  'submit_post': 'Post job',
  'save_changes': 'Save changes',
  'cancel_job': 'Cancel job',
  'cancel_job_prompt': 'Why are you cancelling?',
  'reason_other_worker': 'Found another worker',
  'reason_plans_changed': 'Plans changed',
  'reason_other': 'Other',
  'job_posted': 'Job posted ✓',
  'job_cancelled': 'Job cancelled',
  'no_posted_jobs': 'No jobs yet — tap + to post one',
  'today_digest': "Today's overview",
  'tab_my_jobs': 'My Jobs',
};

// Kannada strings
const Map<String, String> _knStrings = {
  'home': 'ಮನೆ',
  'jobs': 'ಕೆಲಸಗಳು',
  'profile': 'ಪ್ರೊಫೈಲ್',
  'apply': 'ಅರ್ಜಿ ಹಾಕಿ',
  'urgent': 'ತುರ್ತು',
  'open': 'ತೆರೆದಿದೆ',
  'assigned': 'ನಿಯೋಜಿಸಲಾಗಿದೆ',
  'in_progress': 'ನಡೆಯುತ್ತಿದೆ',
  'completed': 'ಮುಗಿದಿದೆ',
  'cancelled': 'ರದ್ದಾಗಿದೆ',
  'worker': 'ನಾನು ಕಾರ್ಮಿಕ',
  'employer': 'ನಾನು ಉದ್ಯೋಗದಾತ',
  'search_grow': 'ಕೆಲಸ ಹುಡುಕಿ ಬೆಳೆಯಿರಿ',
  'recommended': 'ಶಿಫಾರಸು ಮಾಡಿದ ಕೆಲಸಗಳು',
  'my_jobs': 'ನನ್ನ ಪೋಸ್ಟ್ ಮಾಡಿದ ಕೆಲಸಗಳು',
  'per_day': '/ದಿನ',
  'away': 'ದೂರ',
  'workers_needed': 'ಬೇಕಾದ ಕಾರ್ಮಿಕರು',
  'start_date': 'ಪ್ರಾರಂಭ ದಿನಾಂಕ',
  'wage': 'ವೇತನ',
  'description': 'ವಿವರಣೆ',
  'applicants': 'ಅರ್ಜಿದಾರರು',
  'filter': 'ಫಿಲ್ಟರ್',
  'apply_filters': 'ಫಿಲ್ಟರ್ ಅನ್ವಯಿಸಿ',
  'status': 'ಸ್ಥಿತಿ',
  'wage_range': 'ವೇತನ ವ್ಯಾಪ್ತಿ',
  'core_skills': 'ಮೂಲ ಕೌಶಲ್ಯಗಳು',
  'recent_reviews': 'ಇತ್ತೀಚಿನ ವಿಮರ್ಶೆಗಳು',
  'experience': 'ಅನುಭವ',
  'jobs_completed': 'ಮಾಡಿದ ಕೆಲಸಗಳು',
  'reliability': 'ವಿಶ್ವಾಸಾರ್ಹತೆ',
  'applied': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಲಾಗಿದೆ!',
  'apply_success': 'ಅರ್ಜಿ ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ',
  'post_job': 'ಕೆಲಸ ಪೋಸ್ಟ್ ಮಾಡಿ',
  'coming_soon': 'ಶೀಘ್ರದಲ್ಲಿ ಬರಲಿದೆ',
  'years': 'ವರ್ಷ',
  'km_away': '~5 ಕಿ.ಮೀ ದೂರ',
  'reset': 'ಮರುಹೊಂದಿಸಿ',
  'post_job_title': 'ಕೆಲಸ ಪೋಸ್ಟ್ ಮಾಡಿ',
  'edit_job_title': 'ಕೆಲಸ ಸಂಪಾದಿಸಿ',
  'wizard_step_1': 'ಏನು ಮತ್ತು ಎಲ್ಲಿ',
  'wizard_step_2': 'ಯಾವಾಗ ಮತ್ತು ಎಷ್ಟು',
  'wizard_step_3': 'ಪಾವತಿ ಮತ್ತು ದೃಢೀಕರಣ',
  'next': 'ಮುಂದೆ',
  'back': 'ಹಿಂದೆ',
  'cancel': 'ರದ್ದುಗೊಳಿಸಿ',
  'job_category': 'ವರ್ಗ',
  'job_title_field': 'ಕೆಲಸದ ಶೀರ್ಷಿಕೆ',
  'job_description': 'ವಿವರಣೆ (ಐಚ್ಛಿಕ)',
  'pick_location': 'ಸ್ಥಳ ಆಯ್ಕೆಮಾಡಿ',
  'use_my_location': 'ನನ್ನ ಸ್ಥಳ ಬಳಸಿ',
  'adjust_on_map': 'ನಕ್ಷೆಯಲ್ಲಿ ಸರಿಹೊಂದಿಸಿ',
  'type_address': 'ವಿಳಾಸ ಟೈಪ್ ಮಾಡಿ',
  'start_time_field': 'ಪ್ರಾರಂಭ ಸಮಯ',
  'end_time_field': 'ಮುಕ್ತಾಯ ಸಮಯ',
  'end_date': 'ಮುಕ್ತಾಯ ದಿನಾಂಕ',
  'workers_count': 'ಬೇಕಾದ ಕಾರ್ಮಿಕರು',
  'mark_urgent': 'ತುರ್ತು ಎಂದು ಗುರುತಿಸಿ',
  'preview': 'ಮುನ್ನೋಟ',
  'submit_post': 'ಕೆಲಸ ಪೋಸ್ಟ್ ಮಾಡಿ',
  'save_changes': 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
  'cancel_job': 'ಕೆಲಸ ರದ್ದುಗೊಳಿಸಿ',
  'cancel_job_prompt': 'ಏಕೆ ರದ್ದುಗೊಳಿಸುತ್ತಿದ್ದೀರಿ?',
  'reason_other_worker': 'ಬೇರೆ ಕಾರ್ಮಿಕ ಸಿಕ್ಕರು',
  'reason_plans_changed': 'ಯೋಜನೆ ಬದಲಾಯಿತು',
  'reason_other': 'ಇತರೆ',
  'job_posted': 'ಕೆಲಸ ಪೋಸ್ಟ್ ಆಗಿದೆ ✓',
  'job_cancelled': 'ಕೆಲಸ ರದ್ದಾಗಿದೆ',
  'no_posted_jobs': 'ಇನ್ನೂ ಕೆಲಸಗಳಿಲ್ಲ — ಪೋಸ್ಟ್ ಮಾಡಲು + ಒತ್ತಿರಿ',
  'today_digest': 'ಇಂದಿನ ಸಮಾಲೋಚನೆ',
  'tab_my_jobs': 'ನನ್ನ ಕೆಲಸಗಳು',
};

// Provider that returns current strings map
final stringsProvider = Provider<Map<String, String>>((ref) {
  final lang = ref.watch(languageProvider);
  return lang == 'kn' ? _knStrings : _enStrings;
});
